repos:

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.1
    hooks:
      - id: codespell
        name: Checking for spelling issues

  - repo: local
    hooks:
      - id: lint
        name: Running yarn lint to ensure changes will pass linting on CI
        entry:  yarn lint
        language: system
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
